apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: default
  annotations:
    argocd.argoproj.io/tracking-id: flask-app:/Service:default/flask-service
spec:
  type: NodePort
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30036
