apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: flask-app:/Service:default/flask-service
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"flask-app:/Service:default/flask-service"},"name":"flask-service","namespace":"default"},"spec":{"ports":[{"nodePort":30036,"port":80,"protocol":"TCP","targetPort":80}],"selector":{"app":"flask"},"type":"NodePort"}}
  creationTimestamp: "2025-10-27T16:06:13Z"
  name: flask-service
  namespace: default
  resourceVersion: "3468"
  uid: 6527dbf2-1b5c-4e28-a07b-7923b719207d
spec:
  clusterIP: 10.98.244.55
  clusterIPs:
  - 10.98.244.55
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30036
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: flask
  sessionAffinity: None
  type: NodePort
